import type { ContentItem } from "@/lib/types";

export const contents: ContentItem[] = [
  {
    id: "c1",
    clientId: "inovar",
    title: "Reel — Gestão",
    format: "Reels",
    dueLabel: "Hoje",
    dueDate: "2026-09-15",
    responsibleId: "fernanda",
    status: "aprovacao",
  },
  {
    id: "c2",
    clientId: "pleno",
    title: "Carrossel — Resultados do trimestre",
    format: "Carrossel",
    dueLabel: "Amanhã",
    dueDate: "2026-09-16",
    responsibleId: "camila",
    status: "agendado",
  },
  {
    id: "c3",
    clientId: "conservar",
    title: "Post ASG",
    format: "Feed",
    dueLabel: "17/09",
    dueDate: "2026-09-17",
    responsibleId: "bruno",
    status: "producao",
  },
  {
    id: "c4",
    clientId: "felipe-holanda",
    title: "Reel — CEO",
    format: "Reels",
    dueLabel: "18/09",
    dueDate: "2026-09-18",
    responsibleId: "mariana",
    status: "revisao",
  },
  {
    id: "c5",
    clientId: "vero",
    title: "Stories — Campanha outubro rosa",
    format: "Stories",
    dueLabel: "19/09",
    dueDate: "2026-09-19",
    responsibleId: "fernanda",
    status: "producao",
  },
];
