import type { TaskItem } from "@/lib/types";

export const myTasks: TaskItem[] = [
  {
    id: "t1",
    title: "Revisar copy do Reel",
    clientId: "inovar",
    dueLabel: "Hoje",
    dueDate: "2026-09-15",
    priority: "alta",
    status: "pendente",
    assigneeId: "daniel",
  },
  {
    id: "t2",
    title: "Aprovar planejamento",
    clientId: "pleno",
    dueLabel: "Hoje",
    dueDate: "2026-09-15",
    priority: "alta",
    status: "pendente",
    assigneeId: "daniel",
  },
  {
    id: "t3",
    title: "Enviar briefing",
    clientId: "conservar",
    dueLabel: "Amanhã",
    dueDate: "2026-09-16",
    priority: "media",
    status: "pendente",
    assigneeId: "daniel",
  },
  {
    id: "t4",
    title: "Revisar calendário",
    clientId: "felipe-holanda",
    dueLabel: "17/09",
    dueDate: "2026-09-17",
    priority: "baixa",
    status: "pendente",
    assigneeId: "daniel",
  },
  {
    id: "t5",
    title: "Validar relatório de performance",
    clientId: "vero",
    dueLabel: "12/09",
    dueDate: "2026-09-12",
    priority: "alta",
    status: "atrasada",
    assigneeId: "daniel",
  },
];
